version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9092"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8090:8080"

  eureka-server:
    build: ./eureka-server/eureka-server
    ports:
      - "8762:8761"
    depends_on:
      - config-server

  config-server:
    build: ./config-server/config-server
    ports:
      - "8889:8888"
    depends_on:
      - kafka
      - mysql
      - mongodb

  api-gateway:
    build: ./api-gateway/api-gateway
    ports:
      - "8085:8080"
    depends_on:
      - eureka-server

  account-service:
    build: ./account-service/account-service
    ports:
      - "8088:8081"
    depends_on:
      - mysql
      - kafka
      - eureka-server
      - config-server

  transaction-service:
    build: ./transaction-service/transaction-service
    ports:
      - "8087:8082"
    depends_on:
      - mongodb
      - kafka
      - eureka-server
      - config-server

volumes:
  mysql_data:
  mongo_data: 